### PR TITLE
Fix datafusion

### LINKED ISSUE #3: datafusion's benchmark code is wrong
@tustvold 
If I print the row number of each query result, it'll always be 8192 or 0. 
```
for query in QUERIES {
        let start = Instant::now();
        let frame = ctx.sql(query).await.unwrap();
        let mut s = frame.execute_stream().await.unwrap();
        
        let mut rows = 0;
        for batch in s.next().await {
            let b = batch.unwrap();
            rows += b.num_rows();
        }

        let elapsed = start.elapsed();
        println!("rows:{rows}, {} - {}s", query, elapsed.as_secs_f64());
    }
```

```
rows:8192, select * from logs - 0.023356835s
rows:8192, select * from logs where service = 'frontend' - 0.017427552s
rows:8192, select * from logs where service = 'frontend' and host = 'i-1ec3d9e2506434b2.ec2.internal' - 0.01588402s
rows:0, select * from logs where service = 'frontend' and host = 'i-1ec3d9e2506434b2.ec2.internal' and time > '1970-01-01 00:00:00.008000'::timestamp - 0.008340305s
rows:8192, select request_duration_ns from logs - 0.002300762s
rows:8192, select request_duration_ns from logs where service = 'frontend' - 0.006927164s
rows:8192, select request_duration_ns from logs where service = 'frontend' and host = 'i-1ec3d9e2506434b2.ec2.internal' - 0.010156127s
rows:0, select request_duration_ns from logs where service = 'frontend' and host = 'i-1ec3d9e2506434b2.ec2.internal' and time > '1970-01-01 00:00:00.008000'::timestamp - 0.007235235s
rows:8192, select client_addr from logs - 0.004272273s
rows:8192, select client_addr from logs where service = 'frontend' - 0.006822174s
rows:8192, select client_addr from logs where service = 'frontend' and host = 'i-1ec3d9e2506434b2.ec2.internal' - 0.007725965s
rows:0, select client_addr from logs where service = 'frontend' and host = 'i-1ec3d9e2506434b2.ec2.internal' and time > '1970-01-01 00:00:00.008000'::timestamp - 0.007176525s
```

But from duckdb cli, it's `4859858` for the first query:

```
D CREATE VIEW logs AS SELECT *
> FROM read_parquet('/home/sundy/work/access-log-gen/*.parquet');
D select count(1) from logs;
┌──────────┐
│ count(1) │
│  int64   │
├──────────┤
│  4859858 │
└──────────┘
```

### PR DESCRIPTION
**Pull request by tustvold**
Closes #3 

Thank you for the report, this one was stupid :laughing:

### CODE REVIEW

File: datafusion/src/main.rs [hunk 1]
```diff
@@ -41,11 +41,12 @@ async fn main() {
         let frame = ctx.sql(query).await.unwrap();
         let mut s = frame.execute_stream().await.unwrap();
 
-        for batch in s.next().await {
-            batch.unwrap();
+        let mut row_count = 0;
+        while let Some(batch) = s.next().await {
```
Comment (tustvold) [inline datafusion/src/main.rs:45]: Previously this would just take the first RecordBatch returned, i.e. the first 8192 rows.

Fortunately most queries weren't returning more than this, and so it doesn't impact most of the benchmarks, but does explain the somewhat extreme unpredicated scan performance :laughing:

**Review by alamb — COMMENTED** [review]
👍  makes sense to me
